#!/usr/bin/bash

# bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor DP-1-2 -d 6 7 8 9 10

bspc desktop 6 --to-monitor DP-1-2
bspc desktop 7 --to-monitor DP-1-2
bspc desktop 8 --to-monitor DP-1-2
bspc desktop 9 --to-monitor DP-1-2
bspc desktop 10 --to-monitor DP-1-2


# for desktop in $(bspc query -D --names -m eDP-1 | sed 5q); do
#   bspc desktop "$desktop" --to-monitor DP-1-2
# done

# bspc desktop Desktop --remove

# bspc wm -O DP-1-2 eDP-1

