#!/usr/bin/bash

# restart polybar
bash ~/.config/polybar/launch.sh

bspc desktop 6 --to-monitor DP-1-2
bspc desktop 7 --to-monitor DP-1-2
bspc desktop 8 --to-monitor DP-1-2
bspc desktop 9 --to-monitor DP-1-2
bspc desktop 10 --to-monitor DP-1-2

