#!/usr/bin/bash

# bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc desktop 6 --to-monitor eDP-1
bspc desktop 7 --to-monitor eDP-1
bspc desktop 8 --to-monitor eDP-1
bspc desktop 9 --to-monitor eDP-1
bspc desktop 10 --to-monitor eDP-1

